### ISSUE TITLE
invalid_scope | Scope does not match, it may have been tampered with.

### ISSUE THREAD

**Issue by tomtom87** [Shopify/shopify_app#221]
Hi,

I have followed the guide here (https://github.com/Shopify/shopify_app) and tried to configure my development store and localhost so that I can start developing my first shopify app.

The problem is that when I try to install the application. I get the error 

```
invalid_scope | Scope does not match, it may have been tampered with.
```

I have not changed the scopes and do not know how to remedy this issue, please assist how to fix this

Thank you

**Comment by kevinhughes27** [comment]
I believe this is due to this: https://github.com/Shopify/omniauth-shopify-oauth2/pull/38

I am going to close here and ping on the other repo. Thanks for the issue!

**Comment by tomtom87** [comment]
Ok thanks @kevinhughes27 , how do I fix this then?

**Comment by kevinhughes27** [comment]
remove spaces from your scope for the time being or use the patched oauth provider gem. (spaces is easier)

**Comment by tomtom87** [comment]
Ah ok, yeh was wondering how to patch the gem. Thanks alot!

On 23/02/2559 BE 11:14 p.m., Kevin Hughes wrote:
>
> remove spaces from your scope for the time being or use the patched 
> oauth provider gem. (spaces is easier)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Shopify/shopify_app/issues/221#issuecomment-187768676>.
>

-- 
--

Tom Whitbread
Gript.co.uk

**Comment by tomtom87** [comment]
@kevinhughes27 just tested and this is fixed thank you again!

**Comment by kevinhughes27** [comment]
my pleasure!

**Comment by mhoanghold** [comment]
Hi,
I've removed the spaces in my scope definition and I am still getting this error.

**Comment by kevinhughes27** [comment]
a fix has been shipped to the provider gem so you can bump the version in your gemfile to `1.1.13`. Whats is your scope?

**Comment by mhoanghold** [comment]
I have used 1.1.13 and it still fails.

I have it specified as:

  config.scope = "read_products,write_products"

**Comment by kevinhughes27** [comment]
@EiNSTeiN- and @dylanahsmith - still having issues here

**Comment by mhoanghold** [comment]
I've inspected the expected scope and the actual scope. I had previously set write_products as my only scope and then added read_scopes.

When I spit out:

`puts expected_scope.inspect
 puts token['scope'].delete(' ').split(',').sort.inspect`

`["read_products", "write_products"]
["write_products"]`

It seems like the token['scope'] only has the old scope as previously defined or has removed the read_products permission. In my inititalizer, I have:

`config.scope = "read_products,write_products"`

And in my request URL, i have read_products,write_products

**Comment by dylanahsmith** [comment]
Oh, right.  I think the server normalizes the scope by removing read_products on a scope with write_products, since write_products implies read_products.

**Comment by mhoanghold** [comment]
Thanks! Would it possible to update the docs since it still lists read_products separately as a permission?

**Comment by EiNSTeiN-** [comment]
Oh that's right. We should probably normalize the scopes before sending them to shopify and remove these unnecessary ones.

**Comment by kevinhughes27** [comment]
ah of course.

**Comment by EiNSTeiN-** [comment]
Version 1.1.14 was released for your issue @mhoanghold
