### ISSUE TITLE
ShopifyApp::WebhooksManager::CreationFailed

### ISSUE THREAD

**Issue by chintanparikh** [Shopify/shopify_app#263]
Hi all -

I used the provided generators to register webhooks. When I went to auth my development shop, I got the error in the title. Here's my shopify_app.rb

```
ShopifyApp.configure do |config|
  config.api_key = HIDDEN
  config.secret = HIDDEN
  config.scope = "write_products, read_products, write_script_tags"
  config.embedded_app = true
  config.webhooks = [
    {topic: 'app/uninstall', address: 'https://6558fa5c.ngrok.io/webhooks/app_uninstall', format: 'json'},
    {topic: 'products/delete', address: 'https://6558fa5c.ngrok.io/webhooks/products_delete', format: 'json'},
    {topic: 'products/update', address: 'https://6558fa5c.ngrok.io/webhooks/products_update', format: 'json'},
    {topic: 'products/create', address: 'https://6558fa5c.ngrok.io/webhooks/products_create', format: 'json'},
  ]
end
```

Note that I don't have ActiveJob set up as I haven't deployed to production yet. Everything seems right, so I'm not really sure where to start debugging. Any insight would be appreciated.

Here are the relevant server logs:

```
[ActiveJob] Enqueued ShopifyApp::WebhooksManagerJob (Job ID: 6a136b59-a558-45d3-b9fe-8899e8da8064) to Inline(default) with arguments: {:shop_name=>"photopreviewstore.myshopify.com", :token=>"ba215e8644b0fa5960558c958a6e96b6"}
[ActiveJob] [ShopifyApp::WebhooksManagerJob] [6a136b59-a558-45d3-b9fe-8899e8da8064] Performing ShopifyApp::WebhooksManagerJob from Inline(default) with arguments: {:shop_name=>"photopreviewstore.myshopify.com", :token=>"ba215e8644b0fa5960558c958a6e96b6"}
[ActiveJob] [ShopifyApp::WebhooksManagerJob] [6a136b59-a558-45d3-b9fe-8899e8da8064] Performed ShopifyApp::WebhooksManagerJob from Inline(default) in 2564.7ms
Completed 500 Internal Server Error in 3812ms (ActiveRecord: 12.0ms)

ShopifyApp::WebhooksManager::CreationFailed (ShopifyApp::WebhooksManager::CreationFailed):
  shopify_app (7.0.2) lib/shopify_app/webhooks_manager.rb:56:in `create_webhook'
  shopify_app (7.0.2) lib/shopify_app/webhooks_manager.rb:23:in `block (2 levels) in create_webhooks'
  shopify_app (7.0.2) lib/shopify_app/webhooks_manager.rb:22:in `each'
  shopify_app (7.0.2) lib/shopify_app/webhooks_manager.rb:22:in `block in create_webhooks'
  shopify_app (7.0.2) lib/shopify_app/webhooks_manager.rb:49:in `block in with_shopify_session'
  shopify_api (4.0.7) lib/shopify_api/session.rb:30:in `temp'
  shopify_app (7.0.2) lib/shopify_app/webhooks_manager.rb:48:in `with_shopify_session'
  shopify_app (7.0.2) lib/shopify_app/webhooks_manager.rb:21:in `create_webhooks'
  shopify_app (7.0.2) lib/shopify_app/webhooks_manager_job.rb:8:in `perform'
  activejob (4.2.2) lib/active_job/execution.rb:32:in `block in perform_now'
  activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.2) lib/active_support/callbacks.rb:343:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
  activejob (4.2.2) lib/active_job/logging.rb:23:in `call'
  activejob (4.2.2) lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
  activejob (4.2.2) lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
  activejob (4.2.2) lib/active_job/logging.rb:43:in `block in tag_logger'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  activejob (4.2.2) lib/active_job/logging.rb:43:in `tag_logger'
  activejob (4.2.2) lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
  activesupport (4.2.2) lib/active_support/callbacks.rb:441:in `instance_exec'
  activesupport (4.2.2) lib/active_support/callbacks.rb:441:in `block in make_lambda'
  activesupport (4.2.2) lib/active_support/callbacks.rb:342:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:342:in `block in simple'
  activesupport (4.2.2) lib/active_support/callbacks.rb:497:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_perform_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  activejob (4.2.2) lib/active_job/execution.rb:31:in `perform_now'
  activejob (4.2.2) lib/active_job/execution.rb:21:in `execute'
  activejob (4.2.2) lib/active_job/queue_adapters/inline_adapter.rb:14:in `enqueue'
  activejob (4.2.2) lib/active_job/enqueuing.rb:71:in `block in enqueue'
  activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.2) lib/active_support/callbacks.rb:343:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
  activejob (4.2.2) lib/active_job/logging.rb:14:in `call'
  activejob (4.2.2) lib/active_job/logging.rb:14:in `block (3 levels) in <module:Logging>'
  activejob (4.2.2) lib/active_job/logging.rb:43:in `block in tag_logger'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  activejob (4.2.2) lib/active_job/logging.rb:43:in `tag_logger'
  activejob (4.2.2) lib/active_job/logging.rb:13:in `block (2 levels) in <module:Logging>'
  activesupport (4.2.2) lib/active_support/callbacks.rb:441:in `instance_exec'
  activesupport (4.2.2) lib/active_support/callbacks.rb:441:in `block in make_lambda'
  activesupport (4.2.2) lib/active_support/callbacks.rb:342:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:342:in `block in simple'
  activesupport (4.2.2) lib/active_support/callbacks.rb:497:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_enqueue_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  activejob (4.2.2) lib/active_job/enqueuing.rb:67:in `enqueue'
  activejob (4.2.2) lib/active_job/enqueuing.rb:17:in `perform_later'
  shopify_app (7.0.2) lib/shopify_app/webhooks_manager.rb:6:in `queue'
  shopify_app (7.0.2) lib/shopify_app/sessions_concern.rb:22:in `callback'
  actionpack (4.2.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.2) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.2) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.2) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.2) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:408:in `call_app!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:362:in `callback_phase'
  omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:75:in `callback_phase'
  omniauth-shopify-oauth2 (1.1.14) lib/omniauth/strategies/shopify.rb:100:in `callback_phase'
  omniauth (1.3.1) lib/omniauth/strategy.rb:227:in `callback_call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:184:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.3.1) lib/omniauth/builder.rb:63:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.2) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.2) lib/rails/application.rb:164:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by chintanparikh** [comment]
Fixed - it should have been app/uninstalled for the uninstall webhook topic.

**Comment by kevinhughes27** [comment]
Thanks for reporting back.

We should probably create a topic whitelist to help people out here. I've seen this mistake a couple of times recently and it happened to me as well.

**Comment by npupko** [comment]
I faced with this too and still do not understand what the problem may be.
Could anyone help me with this?

My config:
```
ShopifyApp.configure do |config|
  config.application_name = "App Name"
  config.api_key = Settings.shopify.api_key
  config.secret = Settings.shopify.secret
  config.scope = "read_products, read_orders, " \
    "read_themes, write_themes, read_script_tags, write_script_tags, " \
    "read_marketing_events, write_marketing_events, write_orders"

  config.embedded_app = true
  config.after_authenticate_job = { job: AfterAuthenticateJob }

  topics = %w[
    orders/create products/update products/delete app/uninstalled themes/publish
    checkouts/update shop/update
  ]

  config.webhooks = topics.each_with_object([]) do |topic, a|
    options = {
      topic: topic,
      format: "json",
      address: "#{Settings.host}/webhooks/#{topic.parameterize(separator: '_')}"
    }
    a << options
  end
end
```

Trace:
```
ShopifyApp::WebhooksManager::CreationFailed: Address for this topic has already been taken
  from shopify_app/webhooks_manager.rb:49:in `create_webhook'
  from shopify_app/webhooks_manager.rb:28:in `block in create_webhooks'
  from shopify_app/webhooks_manager.rb:27:in `each'
  from shopify_app/webhooks_manager.rb:27:in `create_webhooks'
  from shopify_app/webhooks_manager_job.rb:11:in `block in perform'
  from shopify_api/session.rb:30:in `temp'
  from shopify_app/webhooks_manager_job.rb:9:in `perform'
  from active_job/execution.rb:34:in `block in perform_now'
  from active_support/callbacks.rb:126:in `call'
  from active_support/callbacks.rb:506:in `block (2 levels) in compile'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:448:in `block (2 levels) in around'
  from active_support/callbacks.rb:286:in `block (2 levels) in halting'
  from new_relic/agent/instrumentation/active_job.rb:46:in `perform'
  from new_relic/agent/instrumentation/active_job.rb:20:in `block (3 levels) in <top (required)>'
  from active_support/callbacks.rb:391:in `instance_exec'
  from active_support/callbacks.rb:391:in `block in make_lambda'
  from active_support/callbacks.rb:285:in `block in halting'
  from active_support/callbacks.rb:447:in `block in around'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:448:in `block (2 levels) in around'
  from active_support/callbacks.rb:286:in `block (2 levels) in halting'
  from i18n.rb:257:in `with_locale'
  from active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
  from active_support/callbacks.rb:391:in `instance_exec'
  from active_support/callbacks.rb:391:in `block in make_lambda'
  from active_support/callbacks.rb:285:in `block in halting'
  from active_support/callbacks.rb:447:in `block in around'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:448:in `block (2 levels) in around'
  from active_support/callbacks.rb:286:in `block (2 levels) in halting'
  from active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
  from active_support/notifications.rb:164:in `block in instrument'
  from active_support/notifications/instrumenter.rb:21:in `instrument'
  from active_support/notifications.rb:164:in `instrument'
  from active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
  from active_job/logging.rb:46:in `tag_logger'
  from active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
  from active_support/callbacks.rb:391:in `instance_exec'
  from active_support/callbacks.rb:391:in `block in make_lambda'
  from active_support/callbacks.rb:285:in `block in halting'
  from active_support/callbacks.rb:447:in `block in around'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:101:in `__run_callbacks__'
  from active_support/callbacks.rb:750:in `_run_perform_callbacks'
  from active_support/callbacks.rb:90:in `run_callbacks'
  from active_job/execution.rb:33:in `perform_now'
  from active_job/execution.rb:22:in `block in execute'
  from active_support/callbacks.rb:126:in `call'
  from active_support/callbacks.rb:506:in `block (2 levels) in compile'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:448:in `block (2 levels) in around'
  from active_support/callbacks.rb:286:in `block (2 levels) in halting'
  from active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
  from active_support/execution_wrapper.rb:85:in `wrap'
  from active_support/reloader.rb:68:in `block in wrap'
  from active_support/execution_wrapper.rb:81:in `wrap'
  from active_support/reloader.rb:67:in `wrap'
  from active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
  from active_support/callbacks.rb:391:in `instance_exec'
  from active_support/callbacks.rb:391:in `block in make_lambda'
  from active_support/callbacks.rb:285:in `block in halting'
  from active_support/callbacks.rb:447:in `block in around'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:101:in `__run_callbacks__'
  from active_support/callbacks.rb:750:in `_run_execute_callbacks'
  from active_support/callbacks.rb:90:in `run_callbacks'
  from active_job/execution.rb:20:in `execute'
  from active_job/queue_adapters/sidekiq_adapter.rb:40:in `perform'
  from sidekiq/processor.rb:167:in `execute_job'
  from sidekiq/processor.rb:139:in `block (5 levels) in process'
  from sidekiq/rails.rb:90:in `block in call'
  from active_support/execution_wrapper.rb:85:in `wrap'
  from sidekiq/rails.rb:89:in `call'
  from sidekiq/processor.rb:135:in `block (4 levels) in process'
  from sidekiq/middleware/chain.rb:128:in `block in invoke'
  from sidekiq/throttler.rb:36:in `block in call'
  from sidekiq/throttler/rate_limit.rb:149:in `execute'
  from sidekiq/throttler.rb:43:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
  from new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
  from new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from raven/integrations/sidekiq.rb:7:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/server/logging.rb:10:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/server/retry_jobs.rb:74:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/chain.rb:133:in `invoke'
  from sidekiq/processor.rb:134:in `block (3 levels) in process'
  from sidekiq/logging.rb:32:in `with_context'
  from sidekiq/processor.rb:132:in `block (2 levels) in process'
  from sidekiq/processor.rb:183:in `stats'
  from sidekiq/processor.rb:131:in `block in process'
  from sidekiq.rb:35:in `block in <module:Sidekiq>'
  from sidekiq/processor.rb:126:in `process'
  from sidekiq/processor.rb:82:in `process_one'
  from sidekiq/processor.rb:70:in `run'
  from sidekiq/util.rb:17:in `watchdog'
  from sidekiq/util.rb:26:in `block in safe_thread'
```
