### ISSUE TITLE
Oauth error invalid_request: The redirect_uri is not whitelisted

### ISSUE THREAD

**Issue by Shabbir5253** [Shopify/shopify_app#486]
Whenever I'm trying to install a store in shopify app i'm getting this following error.
![screenshot from 2017-10-13 11 13 18](https://user-images.githubusercontent.com/32759591/31531955-e8c78452-b007-11e7-865d-0b1ce074417c.png)
My app url is:https://c878b023.ngrok.io/
Whitelisted redirection URL:https://c878b023.ngrok.io/auth/shopify/callback/

**Comment by kevinhughes27** [comment]
Can you try adding the plain http url as well? I've found this helps sometimes. It seems to only affect certain people / browsers. If you can figure out exactly what is going on please update us!

**Comment by jamiemtdwyer** [comment]
What is the exact URL that your browser is pointing at in the screenshot?  That's a good starting point.

**Comment by Shabbir5253** [comment]
@kevinhughes27 i had try adding plain http it's not working. Any other suggestions? I'm stuck with this error from past 2 weeks. Any help would be really appreciated.

**Comment by Shabbir5253** [comment]
@jamiemtdwyer http://herosutopia-dev.myshopify.com/

**Comment by jamiemtdwyer** [comment]
To be clear, this is the value of the redirect_uri param at this step of
the installation? and this is the same URL that's whitelisted in your
partner dashboard?

**Comment by Shabbir5253** [comment]
@jamiemtdwyer i'm sorry but i didn't get what exactly you are asking about?

**Comment by Shabbir5253** [comment]
@jamiemtdwyer yes i'm trying to install http://herosutopia-dev.myshopify.com/. But this is not the URL i have specified in partner dashboard. I'm running this app on localhost by using ngrok.

**Comment by jamiemtdwyer** [comment]
I mean the full path of the URL in the address bar including all of the
query parameters. If the value of the redirect_uri parameter doesn't match
what is whitelisted in the partner dashboard, this will need to be
corrected.

**Comment by Shabbir5253** [comment]
@jamiemtdwyer Ok. This is the full path "https://herosutopia-dev.myshopify.com/admin/oauth/authorize?client_id=f93104ed6937d63c9b902bcf8f5e9573&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fshopify%2Fcallback&response_type=code&scope=read_orders%2Cwrite_products%2Cwrite_checkouts&state=0677b4a0eafa7e8c8d2872b4abc7a14c168b0cd6011900d6"

**Comment by kevinhughes27** [comment]
The urls need to match even when doing development. I usually make two api clients - one for development and one for production.

**Comment by jamiemtdwyer** [comment]
The URL whitelisted in your partner dashboard is `https://13f498d3.ngrok.io/auth/shopify/callback/` which does not match the value you are using here: `http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fshopify%2Fcallback` – you will need to whitelist this (or the URI-decoded version) in the partner dashboard.

**Comment by Shabbir5253** [comment]
@jamiemtdwyer Ok let me try.

**Comment by Shabbir5253** [comment]
@jamiemtdwyer It's not working. Thus this error has anything to do with SSL Certification?

**Comment by jamiemtdwyer** [comment]
What isn'T working? You haven't updated the application in your Shopify Partner dashboard. The URL is still `https://d64448da.ngrok.io/auth/shopify/callback/`.

**Comment by Shabbir5253** [comment]
@jamiemtdwyer how did u get to know this URL? And i have updated this URL in my Shopify Partner dashboard.

**Comment by jamiemtdwyer** [comment]
Hi Shabbir5253, I am a member of the Shopify team. 

You can specify multiple values in the redirect whitelist separate by a newline, for your convenience, which means you can whitelist the authentication endpoint on your _localhost_ and your ngrok tunnel. As Kevin said, you can may also want to try whitelisting both `http` and `http`.

**Comment by Shabbir5253** [comment]
@jamiemtdwyer Ok

**Comment by khemrajregmi** [comment]
I am also stuck with the same errors

**Comment by Shabbir5253** [comment]
@jamiemtdwyer  how can specify multiple value in redirect whitelist can you please give me a example??

**Comment by Shabbir5253** [comment]
@jamiemtdwyer @kevinhughes27  I've got the solution. 
I have just added the redirect_uri in omniauth.rb file and it worked.
Thanks for your valuable time.

**Comment by perez9geraldo** [comment]
@Shabbir5253 Could you please share omniauth.rb? I've tried adding redirect_uri in the file, but I still get error.

**Comment by perez9geraldo** [comment]
@Shabbir5253 Resolved my issue by removing the last '/' from redirect uri whitelist in partner dashboard.

**Comment by Shabbir5253** [comment]
@perez9geraldo Great

**Comment by Akki-8388** [comment]
@Shabbir5253 Hello how we removed '/' from dashboard. i am new to Shopify so can you please share.

**Comment by Akki-8388** [comment]
@Shabbir5253 solved issue and get reference from this video **https://developers.shopify.com/app-development**

**Comment by hamedmit** [comment]
Hello friends
I have the same problem. I checked all of the above. There is still a problem. I want to see the localhost but it does not work. Please help me...

**Comment by gopalindians** [comment]
Adding  both
`http://localhost:8000/`
`http://localhost:8000/auth/shopify/callback`
 is working for me.

**Comment by zakeerio** [comment]
Resolved the Problem by Running with this code App successfully Installed.

attr_reader :tokens
  API_KEY = ENV['API_KEY']
  API_SECRET = ENV['API_SECRET']
  APP_URL = "67de3f08.ngrok.io"
  client_id = '8037e820c40a96071c933f9080e6ae39'


  def initialize
    @tokens = {}
    super
  end

  get '/giftbasket/install' do
    shop = request.params['shop']
    scopes = "read_orders,read_products,write_products"

    # construct the installation URL and redirect the merchant
    install_url = "http://#{shop}/admin/oauth/authorize?client_id=#{client_id}"\
                "&scope=#{scopes}&redirect_uri=https://#{APP_URL}/giftbasket/auth"

    # redirect to the install_url
    redirect install_url
  end


In App Partner Account App settings Whitelist the following urls

https://67de3f08.ngrok.io/giftbasket/install
https://67de3f08.ngrok.io/giftbasket/auth
https://67de3f08.ngrok.io/auth/giftbasket/callback

**Comment by benwoodward** [comment]
I had this error, and it was because I am using two api clients, for production and development respectively. The error arises because OAuth is checking against the wrong api client. You can compare the `client_id` URL param against the `config.api_key` value your app is using to see if you're having the same issue. 

If you are using two api clients/partner apps, make sure you are referencing in the correct api key and shared secret. In my case, I was running my app in `development` and the configuration was using the production api key and secret. 

```yaml
development:
        shopify_api_key: <dev partner app api key goes here>
        shopify_shared_secret: <dev partner app shared secret goes here>

production:
        shopify_api_key: <production partner app api key goes here>
        shopify_shared_secret: <production partner app shared secret goes here>
```

```ruby
ShopifyApp.configure do |config|
  config.application_name = "Friendbuy Integration for Shopify"
  config.api_key = Rails.application.credentials[Rails.env.to_sym][:shopify_api_key]
  config.secret = Rails.application.credentials[Rails.env.to_sym][:shopify_shared_secret]
  config.scope = "read_orders, read_customers"
  config.embedded_app = true
  config.after_authenticate_job = false
  config.session_repository = Shop
end
```

**Comment by bhavinjr** [comment]
redirect url is `https` in `install_url` on your code 
so in Whitelisted redirection URL should be `https`
both sould be same either `http` or `https`

**Comment by deepikamk** [comment]
Hi,
I am getting the same issue. I have follow all the above solution but still getting the same. I am using laravel 5.6 and using public app (api key : 4d11173f6d6df76188543beb23fbf3a9). I am able to see no of installed app but screen is showing like
Oops, something went wrong.
What happened?
Oauth error invalid_request: Api client has already been taken
Please help me out asap. As I already wasted 2 days for this and checked all possible ways.

Thanks

**Comment by bhavinjr** [comment]
@deepikamk I had the same issue in laravel 5.6 and I fix that. 
Your Whitelisted redirection URL must be `https`

**Comment by azzouzze** [comment]
have the same issue cant get passed it. 
any help ? code is at MrFochon/flagback

**Comment by Eidher** [comment]
I solved it invalidating the browser cache 🙂

**Comment by Luke-Markham** [comment]
> @deepikamk I had the same issue in laravel 5.6 and I fix that.
> Your Whitelisted redirection URL must be `https`

This worked for me

**Comment by Luke-Markham** [comment]
I keep getting "Internal Server Error" 
any ideas...?

**Comment by frankie90210** [comment]
> The URL whitelisted in your partner dashboard is `https://13f498d3.ngrok.io/auth/shopify/callback/` which does not match the value you are using here: `http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fshopify%2Fcallback` – you will need to whitelist this (or the URI-decoded version) in the partner dashboard.

This approach fixed my  issue - I was able to see its '/auth/callback' not 'auth/shopify/callback'

**Comment by burfbari** [comment]
This was suggested by jamie earlier, but a newbie like me won't be able to deduce it in the first go...
**Check the URL** of the (authentication) page on which you see the error. The URL would contain a parameter called **redirect_uri** 
The value of `redirect_uri`, which is a complete URL has to be present in the Whitelisted redirection URL(s) list. This URL will form depending what is in your code. It could be `localhost` or `ngrok` or any other domain.

**Comment by frankie90210** [comment]
@burfbari this actually easy to do - after you've kicked off install app and get to the problem page, take a look at the url to see the sequence of entries - you should see:forwarding address/auth/callback - then just make sure app set up whitelist url matches that sequence  - give me a shout if still facing issue and explain in more detail what error you are getting

**Comment by burfbari** [comment]
@frankie90210 i was able to do it and was explaining how i did it in my comment for the benefit of others. Thank you anyway for trying to help :-)

**Comment by frankie90210** [comment]
@burfbari oh sorry - and good one you for helping

**Comment by mrdeveloperdude** [comment]
I stumbled upon this problem. I have tried a bunch of different things mentioned in this thread with no effect:

1. Clearing browser cache
2. Using alternate browser (Chrome and FireFox so far)
3. Adding exact url as specified in the **redirect_uri** parameter (sans query parameters) to whitelist
4. Adding entries with both http and https schema to whitelist
5. Adding entries with and without trailing "/" to whitelist
6. Changing API version
7. Making seemingly unrelated changes to app like new icon/name before saving.
8. Sacrifice a virgin goat on the last day of the alignment of Mercury

One important note: **I did NOT make changes to the code.** _It used to work perfectly and then one day out of the blue it did not work._. Last time I can remember it worked was several months ago, probably sometime in late 2019. Shopify devs might be able to look in their logs for this).

Here are some notes that might be relevant:

- My application is written in Python / Flask
- It runs on kubernetes/GKE.
- I have 3 different applications with separate domains (for dev stage and production respectively). I want to attach one test store to each environment. Currently no combination of app/shop works.
- All 3 environment are currently identical
- My https termination happens in nginx using certbot/let's encrypt.
- I use api version 2019-04 exclusively.

I am willing to collaborate with shopify on fixing this if that is an option. Just PM me.

**Comment by ahmadtibrahim** [comment]
> Adding both to
> 
> > Whitelisted redirection URL(s)
> 
> `http://localhost:8000/`
> `http://localhost:8000/auth/shopify/callback`
> works for me.

thank you so much, your solution worked for me as well

**Comment by azzouzze** [comment]
i tried the solution but still no luck. 
still getting the /auth/callback 500 internal server error in ngrok.
and the shopify server throw a webhook creation error below:
Failed to register webhook {
  errors: [
    {
      message: "Invalid url 'undefined/webhooks/products/create', missing host",
      locations: [Array],
      path: [Array],
      extensions: [Object]
    }
  ]
}
  TypeError: Cannot read property 'appSubscriptionCreate' of undefined
      at getSubscriptionUrl (/shopify-demo-app/server/getSubscriptionUrl.js:48:45)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async afterAuth (/shopify-demo-app/server.js:57:9)

any help please ?

**Comment by sky93** [comment]
In my case, my client ID was incorrect. Check it too.

**Comment by TheThai212** [comment]
link is require https and remove last "/" in your link

**Comment by Zakiya-Jafrin** [comment]
> @burfbari this actually easy to do - after you've kicked off install app and get to the problem page, take a look at the url to see the sequence of entries - you should see:forwarding address/auth/callback - then just make sure app set up whitelist url matches that sequence - give me a shout if still facing issue and explain in more detail what error you are getting

This helped me to resolve my issue. apparently in my .env file there was '/' at the end. which was differentiating my redirect URL sequence by putting it as '.......//auth/callback'. it was giving double slash. 

 I removed the last '/' from .env variable and it worked.

**Comment by andreybars20** [comment]
I fixed this problem like this:
Shopify Partners - Apps - Your_App - App Setup - Allowed Redirect URLs - https://url_your_app/auth/callback
For example: https://ddc8-80-72-17-85.ngrok.io/auth/callback

**Comment by blamb888** [comment]
I have tried all of these things and I am still receiving the "Oauth error invalid_request: The redirect_uri is not whitelisted".
.env
HOST=https://cron-job-app.herokuapp.com

Whitelisted urls in the Partners App Admin Panel:
https://cron-job-app.herokuapp.com/
http://cron-job-app.herokuapp.com/auth/callback

And I have my other vars setup on Heroku as well. Any help at all would be appreciated. I was also following the dev tutorial. I've been stuck on this for hours now:(

url on the 400 page: `https://brandon-lambs-store.myshopify.com/admin/oauth/authorize?client_id=bb90acd32e1eef05911ee019150aaa53&scope=write_products%2Cwrite_customers%2Cwrite_draft_orders&redirect_uri=https%3A%2F%2Fcron-job-app.herokuapp.com%2Fauth%2Fcallback&state=331022618173120&grant_options%5B%5D=per-user`

**Comment by marcmedhat6211** [comment]
Okay so I am using the [shopify-api-php](https://github.com/Shopify/shopify-api-php) library to connect to shopify..
I had 2 problems that I had to fix to fix this issue

1. **Problem:** I was giving the full absolute URL as a second parameter to the `Shopify\Auth\OAuth::begin` method
   **Solution:** I had to give only the URL trailing to my Host URL 
   so for example instead of adding "https://784a-156-194-93-4.eu.ngrok.io/api/shopify/auth/callback"
   Just add "/api/shopify/auth/callback"

2. **Problem:** I was adding "https://" in my "SHOPIFY_APP_HOST_NAME" variable in the .env file
   **Solution:** Turns out that the library automatically adds the "https://" when running the `Shopify\Context::initialize` method
   So for example instead of adding "https://784a-156-194-93-4.eu.ngrok.io" in your .env file
   Just add "784a-156-194-93-4.eu.ngrok.io"

**Comment by gregwhitworth** [comment]
I'm hitting this issue but I'm not building the App in the partner portal; I'm building it custom for my own site. Under that location there is no location for whitelisting URLs, etc. But my origin requesting and redirect are correct. My assumption is that I'm missing that whitelist and app url data for my app; does anyone have any ideas?

**Comment by cchoe1** [comment]
Hello, I'd like to post a guide for 2026 on how to implement OAuth using the PHP SDK.  Please note this may be lengthy but I think it's important to not only understand OAuth (to some degree) but also the Shopify ecosystem.  I'm writing this guide here since this page kept showing up during my research and it may help others.  This was my first experience with Shopify's API so I had to trudge through a lot of new topics.  

I first encountered a similar error message to the OP's regarding whitelisted URLs.  However, the problem was not solved by following any of the tips here so I'd like to provide a thorough write up on how I was able to implement this.  

As of this writing, I'm using API Version `2026-01`.  Also note that as of Jan 1, 2026, custom apps are no longer available to create.  You must create an app either using Shopify CLI or using the Dev Dashboard.  The implication being that custom apps had a different authentication scheme than modern options (either a Public Distribution or Custom Distribution - not the same as a custom app!).  Be sure to understand which app structure is relevant for you.  Custom distribution apps require a Shopify Plus account to properly leverage, otherwise you can only install it on one store.  If you are creating an app that needs to be private but you are using Shopify Basic, you can create a public app but choose to do an unlisted distribution.  This will allow you to install on multiple instances of Shopify Basic stores while still keeping it "in-house".  Both public and custom distribution apps require an OAuth flow to obtain an access token which is used to query the GraphQL API.

In my case, I am using Drupal as the backend server.  We have an existing system on Drupal and have plans to expand on it so I've installed the PHP SDK via Composer.  The PHP SDK has the potential to be framework agnostic but you have to write a bit of custom code to make that work.  

For more info, you can visit the Github for the SDK and read some of their docs here to supplement this: [Link](https://github.com/Shopify/shopify-api-php/tree/main/docs)

----

STEP BY STEP GUIDE

1. Create your app.  You can do this with Shopify CLI if you want to create a brand new app. However, if you've been eyeing the PHP SDK, I'm assuming you're probably building on an existing codebase.  If you want to leverage an existing app/platform and add the ability to make API calls to Shopify, you can simply create a new app in the Shopify back end using their basic web form.  
    * Start with the name, more configuration options will follow
    * On the next page, the following fields are important (these can be updated later):
        * App Name - autopopulates from previous step
        * App URL - important if you plan on using the embedded app option
        * Webhook API Version - you will probably leverage webhooks so be sure to select the proper version.  If you're starting new, I recommend the latest version.
        * Access scopes - the types of data you want to pull.  You can modify as you need access to more/different data.
        * Redirect URLs - Very important for OAuth setup.  Be sure to use the full URL including scheme.  For development, you will probably be using ngrok or similar tools to expose your local dev.  So for example, your redirect may be something like `https://1234abcd.ngrok.app/auth/callback`.
    * Click on Release at the bottom to create your first version.  You can create new versions if you need to change anything here.
2.  On the left menu, click on 'Home' to go back to the home page.  Then, look for the "Distribution" section towards the middle of the page.  It's important you select the proper distribution here or else you'll have to redo Step 1 because you cannot change your choice.
    * Public distribution - If you are not on Shopify Plus, this may be the best option for you (even for a private app).  This allows you to install your app on multiple separate stores regardless of plan.  If your setup is multiple Shopify Basic stores, I'd recommend this option.  However, there is the caveat that public apps require an approval process + specific requirements in functionality to be approved for distribution.  However, if you are not on Shopify Plus, this is mostly unavoidable.
    * Custom distribution - Not the same as a custom app (which no longer is possible to create).  This is mainly for Shopify Plus.  If you have Plus, you can install your app on any store within your Plus organization.  Note that development stores grant you extra functionality that you may not have after you transfer ownership and start paying.  So even if it seems to work when installing on development stores, once you transfer ownership, the app will disappear and will not be allowed to install again.
3.  Your app is ready to go.  However, do NOT manually install this app on any of your development stores.  This will prevent the OAuth flow from working correctly (and it was actually the source of my "Redirect URI is not whitelisted" error).  If you manually install the app on a store and then attempt to retrieve an access token via OAuth, you will receive the error in the OP (yes, it's very confusing).  

Now, it's time to write some code using the PHP SDK.  

1.  As stated in the README on the SDK, you will first start by calling \Shopify\Context::initialize().  You must do this before trying to use any other features of the SDK so you should create a reusable function that pulls the relevant values from your environment variables/other configuration.  Details below:


    \Shopify\Context::initialize(
      apiKey: string - This is the CLIENT ID
      apiSecretKey: string - The secret (right below where you see the Client ID in the Dev Dashboard)
      scopes:  string|array - You can grab this from the 'versions' page, i.e. `"read_products,write_products"`
      sessionStorage: SessionStorage - More info below, must implement the Shopify interface
      apiVersion: string - Can be found in the 'versions' page on your Shopify app, i.e. "2026-01"
      isEmbeddedApp: bool - True if you selected embedded app during app setup
      isPrivateApp: bool - I believe this is based on whether you select a "Public" or "Custom" distribution.
      userAgentPrefix: string - Not too important for my case
      logger: LoggerInterface - Also not important for a basic implementation
    );


Below is my implementation of `Context::initialize()` using a Drupal service (see comments on individual lines for more details)

```

final class ShopifyService  {

  public Node $storefront;

  public const SHOPIFY_SCOPES = ["read_products,write_products"];

  public const SHOPIFY_API_VERSION = '2026-01';

  public string $SHOPIFY_API_KEY = '';
  public string $SHOPIFY_API_SECRET = '';
  public string $SHOPIFY_HOSTNAME = '';
  public string $APP_HOSTNAME = '';

  /**
   * Constructs a ShopifyService object.
   */
  public function __construct( // this constructor is Drupal's dependency injection.  May be irrelevant for your framework but the important thing is that we create an instance of the ShopifySessionStorageService class
    private readonly EntityTypeManagerInterface $entityTypeManager,
    private readonly ShopifySessionStorageService $shopify_session_storage_service
  ) {

  }

  public function initialize(Node $storefront) {
    // First check that the store has the proper configuration
    $this->storefront = $storefront;

    $shopify_api_key = $storefront->get('field_shopify_api_key')->value;

    $shopify_api_secret = $storefront->get('field_shopify_api_secret')->value;

    $shopify_hostname = $storefront->get('field_shopify_hostname')->value;

    $app_hostname = '1234abcd.ngrok.app'; // This is the hostname of your custom app, not the shopify store name.  For local dev, you may be using ngrok to expose local dev so your ngrok url would go here

    $this->SHOPIFY_API_KEY = $shopify_api_key; // Client ID
    $this->SHOPIFY_API_SECRET = $shopify_api_secret; // Secret
    $this->SHOPIFY_HOSTNAME = $shopify_hostname; // Your shopify hostname, e.g. myshop.myshopify.com
    $this->APP_HOSTNAME = $app_hostname; // the app hostname, e.g. ngrok, your production URL, etc.

    $this->shopify_session_storage_service->setContext($this->storefront); // this is a custom method I wrote, not setting Shopify context.  See below for the ShopifySessionStorageService class


    Context::initialize(
      $shopify_api_key,
      $shopify_api_secret,
      self::SHOPIFY_SCOPES,
      $app_hostname,
      $this->shopify_session_storage_service, // see below for more details on this
      self::SHOPIFY_API_VERSION,
      FALSE,
      FALSE
    );

  }


}

```

To expand on above, you must provide a class that implements SessionStorage for arg 4.  The important thing here is that you are saving the data somewhere whilst implementing the interface.  There are 3 main methods you must implement:  `storeSession`, `loadSession`, and `deleteSession`.  Below is my implementation (some Drupalisms but try and understand the general idea):

```
final class ShopifySessionStorageService implements SessionStorage { // you must implement the SessionStorage interface provided by the SDK

  public Node $storefront;

  public function __construct(
    private readonly EntityTypeManagerInterface $entityTypeManager,
    private readonly RequestStack $requestStack,
  ) {}

  public function setContext(Node $storefront) {
    $this->storefront = $storefront;
  }

  public function getSessionKey() {
    $storefront_id = $this->storefront->id();

    $key = "shopify-session--$storefront_id";

    return $key;
  }

  /**
   *  Below are some session handling functions
   */
  public function storeSession(Session $session_data): bool
  {
    $session = \Drupal::request()->getSession();

    $session_key = $this->getSessionKey();

    try {
      $session->set($session_key, $session_data);
    }
    catch (\Exception $e) {
      \Drupal::logger('shopify')->error($e->getMessage());
      return FALSE;
    }

    return TRUE;
  }

  public function loadSession(string $sessionId): ?\Shopify\Auth\Session
  {
    $session = \Drupal::request()->getSession();
    $session_key = $this->getSessionKey();


    $session_data = $session->get($session_key);

    return $session_data;
  }

  public function deleteSession(string $sessionId): bool
  {
    $session = \Drupal::request()->getSession();
    $session_key = $this->getSessionKey();

    $session->remove($session_key);

    return TRUE;
  }
}
```

Above, `setContext` and `getSessionKey` are helper functions I created and aren't necessary.  Basically, I'm using Drupal's session management to store this data.  It's keyed by the general format `shopify-session--{storefront_id}`, which my helper function helps define.  This returns a Shopify Session.  I save some store-related data on a Storefront entity so I load that entity to retrieve some data like the Shop name (i.e. mystore.myshopify.com), API key, and API Secret.  Be sure that you keep this data secure and not publicly visible.  You then pass an INSTANCE of this class to `Context::initialize()`.

2.  Create a route to perform the first step of OAuth.  In my case, my route is `/shopify/{storefront_id}/login`.  Here you will call `OAuth::begin()` which returns a URL to Shopify's website where you will start the OAuth flow.  Visit this route to begin OAuth. Below is my implementation.  Please see comments on individual lines for more details

```
  public function login($storefront_id=NULL): RedirectResponse {

    /** @var Node $storefront */
    $storefront = \Drupal::entityTypeManager()->getStorage('node')->load($storefront_id); // Drupal automatically provides the $storefront_id parameter based on the URL slug

    $this->shopifyService->initialize($storefront); // this is referring to a custom service I created.  See above for code.
    $hostname = $this->shopifyService->SHOPIFY_HOSTNAME; // this is the SHOP ID (mystore.myshopify.com).  Do not specify scheme

    $response = new TrustedRedirectResponse('google.com');

    $url = OAuth::begin(
      $hostname,
      '/shopify/auth/callback', // this can be confusing - do not provide scheme or host here, only the path.  This path should match your Redirect URIs in the app setup (versions page).  So here, I would have a whitelisted Redirect URI of `https://1234abcd.ngrok.app/shopify/auth/callback` in my app configuration.
      FALSE, // isOnline - your decision here depends on your app see [this page](https://shopify.dev/docs/apps/build/authentication-authorization/access-tokens/online-access-tokens) for more info.
      function(OAuthCookie $cookie) use ($response) {

        // This callable will receive a OAuthCookie object from the SDK.  When redirecting to the OAuth page, your response must contain the relevant cookies or else you will receive an error about "60 seconds may have passed since you began OAuth" (pp).  
        // Outside of this closure, we initialize a TrustedRedirectResponse (since we're going off site, it's a Symfony/Drupal thing) and then bind to the scope.  I used google.com for the constructor since it's not that important but requires a valid string.  We overwrite that at the end.  
        // On this response, we set cookies using the cookie that was passed into this callable from the SDK.  Your implementation will probably look very similar, especially if you're on a Symfony based framework).
        $response->headers->setCookie(
          new Cookie(
            $cookie->getName(),
            $cookie->getValue(),
            $cookie->getExpire(),
            '',
            '',
            $cookie->isSecure(),
            $cookie->isHttpOnly(),
          )
        );

        return TRUE;
      }
    );


    return $response
      ->setTrustedTargetUrl($url)
      ->addCacheableDependency((new CacheableMetadata())->setCacheMaxAge(0));

  }
```

The difficult part above may be the `setCookieFunction` (parameter 4 of OAuth::begin()).  If you are using a custom framework that doesn't utilize the PHP built in `setcookie()` function (like Drupal), you will need to write a custom implementation.  See my code above.   If you receive an error about too much time having passed since you began OAuth, there is a good chance you are not properly setting the cookies on the response.  

OAuth::begin() will return a URL that you need to redirect the user to (if you're the admin setting this all up for your stores, you'll probably go through this step yourself).  That redirect should contain the cookies passed in from the SDK.  You should see 2 cookies on the request, `shopify_app_state_sig` and `shopify_app_state`.  

3.  You will be redirected to a Shopify page that looks like your classic OAuth approval page.  This is where you actually install the app onto your Shopify store.  If you run into errors at any point during your implementation, you will need to uninstall the app on the shopify store, revisit your login route (in my case, `/shopify/{storefront_id}/login`, and reapprove/reinstall the app.  

    * NOTE:  Read step 4 as you need a 2nd route in place before installing will work correctly.  If you don't have this route in place and try to install, it won't work fully and you'll have to uninstall/reinstall the app again.  

<img width="875" height="579" alt="Image" src="https://github.com/user-attachments/assets/e010c773-5a2e-4e0d-a5b5-4b8da5d647b2" />

4.  Implement the redirect route.  Above, you set a redirect URI like `/shopify/auth/callback` (arg 2 of `OAuth::begin()`).  Now you need to create a route for this path.  The important thing here is to implement OAuth::callback().  If you've configured cookies correctly, this should go smoothly.  If not, you will get an error about your OAuth session having expired.  See my implementation below:

```
  public function redirectPath() {
    $request = \Drupal::request();
    $shop = $request->query->get('shop'); // the shop ID gets passed as a query param, i.e. mystore.myshopify.com

    // Loading my storefront entity to grab some config values and setup my ShopifyService class, this is moreso specific to my implementation
    $storefront = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties([
      'field_shopify_hostname' => $shop,
    ]); 

    if (!($storefront = reset($storefront))) {
      // Handle error gracefully
    }

    $this->shopifyService->initialize($storefront); // This is a custom method which calls Context::initialize(), remember you must initialize before using the Shopify SDK

    // OAuth::callback() returns a Shopify Session which will contain your accessToken.  This accessToken is ultimately what you need to call the GraphQL API
    $session = OAuth::callback(
      $_COOKIE, // I'm simply passing the global var which should contain the cookies you passed in earlier
      $request->query->all(), // This is all the query parameters from the request
    );

    return new Response('Connection successful.  You may now close this window.');
  }
```

5.  Great job if you've made it this far.  Your implementation is basically done.  The SDK will store the Shopify Session using the SessionStorage interface (arg 5 of Context::initialize()) that you defined.  You can retrieve this data to get the Shopify Session 
which will contain your accessToken.  Simply grab that value and then you can make a call to the GraphQL API.  Below is a simple test function I wrote to test the connectivity.  

```
  public function test() {
    $storefront_id = 4;
    $storefront = \Drupal::entityTypeManager()->getStorage('node')->load($storefront_id);

    // Again, this is my helper function that wraps around Context::initialize() but remember you must always call that method before using the SDK
    $this->shopifyService->initialize($storefront);

    /** @var Session $session */
    $session = \Drupal::request()->getSession()->get('shopify-session--'. $storefront_id);

    $client = new \Shopify\Clients\Graphql($session->getShop(), $session->getAccessToken());

    $response = $client->query('
        query productQuery {
          products (first:10) {
            edges {
              node {
                id
                title
              }
            }
            pageInfo {
              endCursor
              startCursor
            }
          }
  
        }
    ');
  }
```

Voila, hopefully you should receive a response back from the GraphQL api and it should match the response you get when debugging via Graphiql.  And on that note, I mentioned at the start that you may not need to create a Shopify app with Shopify CLI.  However, one benefit is that it spins up a local environment that gives you access to GraphiQL (a visual UI to prototype your graphql requests).  If you create the app in the Shopify back-office, you can come back later and spin up an app with Shopify CLI and simply link it to your existing app.  Then you can run `shopify app dev` and it'll spin up a local dev where you can play around with GraphiQL.  

If you have a similar setup to my org, we are managing multiple Shopify Basic stores that are otherwise independent from each other.  Shopify Plus is not quite right for our organization.  So to finish my onboarding, I will repeatedly visit `/shopify/{storefront_id}/login` with all of my stores.  Each store has a Storefront entity in our system that we'll be saving data to.  And then we simply visit this page using all the storefront ids to install the app on their store.  Our system will key the sessions using the storefront id so that we can push/pull data for all of our stores.  

Some topics I didn't touch on are Refresh tokens but I think once you can get this far, the rest is much simpler and at least you have a working implementation to refer back to.  I also didn't touch on proper ways to store sensitive data like the API secret.  The Client ID is not so sensitive and it's publicly exposed at points.  But the secret should be kept secure and hidden, if you expose this at any point (including it in Git, etc.) then you can rotate this key out.  To facilitate secret rotation, you probably want to store this data as an environment variable so that you can easily reset it without having to do deployments or anything time consuming.  

Also, my code here is a bit rough, I got the basic implementation working but I think there is still some work left to do with error handling.  I edited a few things on the fly but I believe all code snippets should be in tact.  I noticed a couple of spots where I didn't reuse certain methods and rewrote existing logic but hopefully the general idea gets across.
